image: 
  file: Dockerfile
# run commands
tasks:
  -name: Install dependency
   init: cd /cv_creater
   command: bunde install && rails db:migrate

  -name: Start Server
  init: cd /cv_creater
  command: rails s -b 0.0.0.0
  openMode: split-right
  posts:
    - 3000