default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  # database: db/production.sqlite3
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
  encoding: unicode
  database: <%= ENV['DATABASE_DB'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>