# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: floppy.db.elephantsql.com
  port: 5432
  username: baopyjej
  password: wvUDOEy_lxW17rktwr7IuGc5URNAs4Km

development:
  <<: *default
  # database: db/development.sqlite3
  database: baopyjej

production:
  <<: *default
  # database: db/production.sqlite3
  database: baopyjej